ALTER POLICY "ad_accounts_select_own" ON "ad_accounts" TO app_user USING ("ad_accounts"."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "ad_accounts_insert_own" ON "ad_accounts" TO app_user WITH CHECK ("ad_accounts"."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "ad_accounts_update_own" ON "ad_accounts" TO app_user USING ("ad_accounts"."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("ad_accounts"."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "ad_accounts_delete_own" ON "ad_accounts" TO app_user USING ("ad_accounts"."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "uploads_select_own" ON "creative_asset_uploads" TO app_user USING ("creative_asset_uploads"."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "uploads_insert_own" ON "creative_asset_uploads" TO app_user WITH CHECK ("creative_asset_uploads"."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "uploads_update_own" ON "creative_asset_uploads" TO app_user USING ("creative_asset_uploads"."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("creative_asset_uploads"."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tokens_select_own" ON "oauth_tokens" TO app_user USING ("oauth_tokens"."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tokens_insert_own" ON "oauth_tokens" TO app_user WITH CHECK ("oauth_tokens"."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tokens_update_own" ON "oauth_tokens" TO app_user USING ("oauth_tokens"."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("oauth_tokens"."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "tokens_delete_own" ON "oauth_tokens" TO app_user USING ("oauth_tokens"."user_id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "users_select_own" ON "users" TO app_user USING ("users"."id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid);--> statement-breakpoint
ALTER POLICY "users_update_own" ON "users" TO app_user USING ("users"."id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid) WITH CHECK ("users"."id" = NULLIF(current_setting('app.current_user_id', true), '')::uuid);