#!/usr/bin/env node

/**
 * CSP Hash Generator
 *
 * This utility automatically calculates SHA-256 hashes for inline scripts
 * from src/utils/uploadTemplates.ts and writes them to src/generated/cspHashes.ts.
 *
 * Follows 2025 staff+ engineering best practices:
 * - Auto-discovers all *_SCRIPT constants (zero manual maintenance)
 * - Generates aggregate array for dynamic CSP configuration
 * - TypeScript for build tooling consistency
 *
 * Usage: tsx scripts/generateCSPHashes.ts
 */

import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const sourcePath = path.resolve(__dirname, '../src/utils/uploadTemplates.ts');
const outputPath = path.resolve(__dirname, '../src/generated/cspHashes.ts');

/**
 * Calculate SHA-256 hash for CSP compliance
 */
function calculateHash(scriptContent: string): string {
  const hash = crypto.createHash('sha256').update(scriptContent.trim()).digest('base64');
  return `"'sha256-${hash}'"`;
}

/**
 * Auto-discover and extract all script constants from TypeScript source file
 * Uses regex to find all constants matching the pattern `*_SCRIPT`
 */
async function loadScripts(): Promise<Record<string, string>> {
  try {
    const sourceCode = await fs.readFile(sourcePath, 'utf8');
    const scripts: Record<string, string> = {};

    // Regex to find all constants ending in `_SCRIPT` and capture their names and content
    const regex = /const (\w+_SCRIPT) = `([\s\S]*?)`;/g;
    let match: RegExpExecArray | null;

    // biome-ignore lint/suspicious/noAssignInExpressions: Standard pattern for regex iteration
    while ((match = regex.exec(sourceCode)) !== null) {
      const scriptName = match[1];
      const scriptContent = match[2].trim();
      scripts[scriptName] = scriptContent;
      console.info(`   Found script: ${scriptName}`);
    }

    if (Object.keys(scripts).length === 0) {
      console.warn(' ! No script constants matching pattern `*_SCRIPT` were found.');
    } else {
      console.info(`   Discovered ${Object.keys(scripts).length} script constants automatically`);
    }

    return scripts;
  } catch (error) {
    console.error('! Error reading TypeScript source file:', (error as Error).message);
    process.exit(1);
  }
}

/**
 * Generate the TypeScript file content with CSP hash exports and aggregate array
 */
function generateFileContent(hashes: Record<string, string>): string {
  const header = `// Auto-generated by scripts/generateCSPHashes.ts - DO NOT EDIT MANUALLY
// Generated at ${new Date().toISOString()}

/**
 * Contains the SHA-256 hashes for inline scripts used in the application.
 * These are used to enforce a strict Content Security Policy (CSP).
 */
`;

  const hashEntries = Object.entries(hashes);
  const exports = hashEntries.map(([key, value]) => `export const ${key} = ${value};`).join('\n');

  // Staff+ Enhancement: Export an array of all hashes for dynamic CSP configuration
  const allHashesArray = `\n/**
 * Array containing all script hashes for dynamic CSP configuration.
 * Eliminates the need to manually maintain the scriptSrc array.
 */
export const ALL_SCRIPT_HASHES = [
  ${hashEntries.map(([key]) => key).join(',\n  ')}
];`;

  return `${header}\n${exports}${allHashesArray}\n`;
}

/**
 * Main function that orchestrates the hash generation process
 */
async function main(): Promise<void> {
  console.info('Generating CSP hashes with auto-discovery...');

  // 1. Auto-discover script constants (zero manual maintenance)
  const scripts = await loadScripts();

  // 2. Process data (calculate hashes)
  const hashes: Record<string, string> = {};
  for (const [scriptName, scriptContent] of Object.entries(scripts)) {
    if (scriptContent) {
      // Create a descriptive key for the exported constant
      const hashKey = `${scriptName}_HASH`;
      hashes[hashKey] = calculateHash(scriptContent);
    }
  }

  if (Object.keys(hashes).length === 0) {
    console.warn(' ! No script hashes were generated. Output file will not be created.');
    return;
  }

  // 3. Generate file content with aggregate array
  const fileContent = generateFileContent(hashes);

  // 4. Write the file
  await fs.writeFile(outputPath, fileContent, 'utf8');

  // 5. Log results
  console.info(`CSP hashes generated successfully at: ${outputPath}`);
  console.info(`   Generated ${Object.keys(hashes).length} hashes with aggregate array.`);
}

// Only run if this script is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error) => {
    console.error('! CSP hash generation failed:', error);
    process.exit(1); // Ensure non-zero exit code on error
  });
}
