import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { AdAccount, AdSet, Campaign } from 'facebook-nodejs-business-sdk';
import { z } from 'zod';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outputPath = path.resolve(__dirname, '../src/generated/schemas.ts');

/**
 * Creates a Zod schema from a Meta SDK field definition object.
 * Since Meta API fields can be strings, numbers, objects, arrays, or null,
 * we use a flexible union type for each field.
 *
 * @param {object} fields - The .Fields object from a Meta SDK class (e.g., Campaign.Fields).
 * @returns {z.ZodObject} - The generated Zod schema.
 */
const generateSchemaFromFields = (fields) => {
  const shape = {};

  // Flexible field type that can handle various Meta API response types
  const flexibleField = z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.object({}).passthrough(),
      z.array(z.unknown()),
      z.null(),
    ])
    .optional();

  for (const fieldName of Object.values(fields)) {
    shape[fieldName] = flexibleField;
  }

  return z.object(shape).passthrough();
};

// Generate base Zod schemas from Meta SDK field definitions
const MetaCampaignResponseSchema = generateSchemaFromFields(Campaign.Fields);
const MetaAdSetResponseSchema = generateSchemaFromFields(AdSet.Fields);
const MetaAdAccountResponseSchema = generateSchemaFromFields(AdAccount.Fields);

// Create list response schemas
const _CampaignListResponseSchema = z.object({
  campaigns: z.array(MetaCampaignResponseSchema),
  paging: z
    .object({
      cursors: z
        .object({
          before: z.string().optional(),
          after: z.string().optional(),
        })
        .optional(),
      next: z.string().optional(),
      previous: z.string().optional(),
    })
    .optional(),
});

const _AdSetListResponseSchema = z.object({
  adSets: z.array(MetaAdSetResponseSchema),
  paging: z
    .object({
      cursors: z
        .object({
          before: z.string().optional(),
          after: z.string().optional(),
        })
        .optional(),
      next: z.string().optional(),
      previous: z.string().optional(),
    })
    .optional(),
});

const _AdAccountListResponseSchema = z.object({
  accounts: z.array(MetaAdAccountResponseSchema),
  paging: z
    .object({
      cursors: z
        .object({
          before: z.string().optional(),
          after: z.string().optional(),
        })
        .optional(),
      next: z.string().optional(),
      previous: z.string().optional(),
    })
    .optional(),
});

// Generate the TypeScript file content
const fileContent = `// Auto-generated by scripts/generateSchemas.js - DO NOT EDIT MANUALLY
// Generated from Meta SDK field definitions at ${new Date().toISOString()}

import { z } from 'zod';

// Flexible field type for Meta API responses
const MetaFlexibleField = z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.object({}).passthrough(),
  z.array(z.unknown()),
  z.null()
]).optional();

// Campaign fields: ${Object.keys(Campaign.Fields).length} total
export const MetaCampaignResponseSchema = z.object({
${Object.values(Campaign.Fields)
  .map((field) => `  ${field}: MetaFlexibleField,`)
  .join('\n')}
}).passthrough();

// AdSet fields: ${Object.keys(AdSet.Fields).length} total  
export const MetaAdSetResponseSchema = z.object({
${Object.values(AdSet.Fields)
  .map((field) => `  ${field}: MetaFlexibleField,`)
  .join('\n')}
}).passthrough();

// AdAccount fields: ${Object.keys(AdAccount.Fields).length} total
export const MetaAdAccountResponseSchema = z.object({
${Object.values(AdAccount.Fields)
  .map((field) => `  ${field}: MetaFlexibleField,`)
  .join('\n')}
}).passthrough();

// List response schemas
export const CampaignListResponseSchema = z.object({
  campaigns: z.array(MetaCampaignResponseSchema),
  paging: z.object({
    cursors: z.object({
      before: z.string().optional(),
      after: z.string().optional()
    }).optional(),
    next: z.string().optional(),
    previous: z.string().optional()
  }).optional()
});

export const AdSetListResponseSchema = z.object({
  adSets: z.array(MetaAdSetResponseSchema),
  paging: z.object({
    cursors: z.object({
      before: z.string().optional(),
      after: z.string().optional()
    }).optional(),
    next: z.string().optional(),
    previous: z.string().optional()
  }).optional()
});

export const AdAccountListResponseSchema = z.object({
  accounts: z.array(MetaAdAccountResponseSchema),
  paging: z.object({
    cursors: z.object({
      before: z.string().optional(),
      after: z.string().optional()
    }).optional(),
    next: z.string().optional(),
    previous: z.string().optional()
  }).optional()
});

// Meta API operation response schemas
export const MetaCreateSuccessResponseSchema = z.object({
  id: z.string(),
}).passthrough();

export const MetaUpdateSuccessResponseSchema = z.object({
  success: z.boolean(),
}).passthrough();

export const MetaDeleteSuccessResponseSchema = z.object({
  success: z.boolean(),
}).passthrough();
`;

// Write the generated schemas to the output file
fs.writeFileSync(outputPath, fileContent, 'utf8');
