#!/usr/bin/env node

/**
 * CSP Hash Generator
 *
 * This utility automatically calculates SHA-256 hashes for inline scripts
 * from src/utils/uploadTemplates.ts and writes them to src/generated/cspHashes.ts.
 *
 * Follows the same pattern as generateSchemas.js for consistency.
 *
 * Usage: node scripts/generateCSPHashes.js
 */

import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const sourcePath = path.resolve(__dirname, '../src/utils/uploadTemplates.ts');
const outputPath = path.resolve(__dirname, '../src/generated/cspHashes.ts');

// Script constants to extract from uploadTemplates.ts
const SCRIPT_CONSTANTS = [
  'AI_COPY_SCRIPT',
  'UPLOAD_FORM_SCRIPT',
  'SUCCESS_SESSION_NOT_FOUND_SCRIPT',
  'FAILED_PAGE_SCRIPT',
  'SERVER_ERROR_SCRIPT',
];

/**
 * Calculate SHA-256 hash for CSP compliance
 */
function calculateHash(scriptContent) {
  const hash = crypto.createHash('sha256').update(scriptContent.trim()).digest('base64');
  return `"'sha256-${hash}'"`;
}

/**
 * Extract script constants from TypeScript source file
 */
async function loadScripts() {
  try {
    const sourceCode = await fs.readFile(sourcePath, 'utf8');
    const scripts = {};

    // First pass: extract all script constants
    for (const scriptName of SCRIPT_CONSTANTS) {
      // Match: const SCRIPT_NAME = `...`; and capture group 1
      const regex = new RegExp(`const ${scriptName} = \`([\\s\\S]*?)\`;`); // No 'g' flag
      const match = sourceCode.match(regex);

      if (match?.[1]) {
        // Check for the captured group
        scripts[scriptName] = match[1].trim();
      } else {
        console.warn(` ! Could not find ${scriptName} in source file`);
        scripts[scriptName] = '';
      }
    }

    // Second pass: expand template literals (${AI_COPY_SCRIPT}, etc.)
    for (const scriptName of SCRIPT_CONSTANTS) {
      let script = scripts[scriptName];
      
      // Replace template literal references with actual content
      for (const refScriptName of SCRIPT_CONSTANTS) {
        const templateRef = `\\$\\{${refScriptName}\\}`;
        const regex = new RegExp(templateRef, 'g');
        script = script.replace(regex, scripts[refScriptName]);
      }
      
      scripts[scriptName] = script;
    }

    return scripts;
  } catch (error) {
    console.error('! Error reading TypeScript source file:', error.message);
    process.exit(1);
  }
}

/**
 * Generate the TypeScript file content with CSP hash exports
 */
function generateFileContent(hashes) {
  const header = `// Auto-generated by scripts/generateCSPHashes.js - DO NOT EDIT MANUALLY
// Generated at ${new Date().toISOString()}

/**
 * Contains the SHA-256 hashes for inline scripts used in the application.
 * These are used to enforce a strict Content Security Policy (CSP).
 */
`;

  const exports = Object.entries(hashes)
    .map(([key, value]) => `export const ${key} = ${value};`)
    .join('\n');

  return `${header}\n${exports}\n`;
}

/**
 * Main function that orchestrates the hash generation process
 */
async function main() {
  console.info('Generating CSP hashes from script constants...');

  // 1. Extract script content
  const scripts = await loadScripts();

  // 2. Process data (calculate hashes)
  const hashes = {};
  for (const [scriptName, scriptContent] of Object.entries(scripts)) {
    if (scriptContent) {
      // Create a descriptive key for the exported constant
      const hashKey = `${scriptName}_HASH`;
      hashes[hashKey] = calculateHash(scriptContent);
    }
  }

  if (Object.keys(hashes).length === 0) {
    console.warn(' ! No script hashes were generated. Output file will not be created.');
    return;
  }

  // 3. Generate file content
  const fileContent = generateFileContent(hashes);

  // 4. Write the file
  await fs.writeFile(outputPath, fileContent, 'utf8');

  // 5. Log results
  console.info(`CSP hashes generated successfully at: ${outputPath}`);
  console.info(`   Generated ${Object.keys(hashes).length} hashes.`);
}

// Only run if this script is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error) => {
    console.error('! CSP hash generation failed:', error);
    process.exit(1); // Ensure non-zero exit code on error
  });
}
